#!/usr/bin/env python3
"""
CIPHERTRACE Automated Security Regression Audit Suite
===================================================
Enforces strict anti-regression rules to prevent security vulnerabilities
and false cryptographic claims from re-entering the repository.

Exits with code 0 if all rules pass, or non-zero exit code if any rule fails.
"""

import os
import sys
import re
import sqlite3

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BACKEND_DIR = os.path.join(ROOT_DIR, "backend")
sys.path.insert(0, BACKEND_DIR)

PASS = "[PASS]"
FAIL = "[FAIL]"


def log_result(rule_name: str, passed: bool, detail: str = ""):
    status = PASS if passed else FAIL
    print(f"{status} Rule: {rule_name}")
    if detail:
        print(f"       -> {detail}")
    return passed


def main():
    print("=" * 80)
    print("      CIPHERTRACE AUTOMATED SECURITY REGRESSION AUDIT (SIH 2026)      ")
    print("=" * 80)

    failures = 0

    # --------------------------------------------------------------------------
    # Rule 1: No classical asymmetric algorithms imported or used as PQC
    # --------------------------------------------------------------------------
    import ast
    crypto_engine_path = os.path.join(BACKEND_DIR, "app", "services", "crypto_engine.py")
    with open(crypto_engine_path, "r", encoding="utf-8") as f:
        crypto_code = f.read()

    tree = ast.parse(crypto_code)
    imported_symbols = set()
    function_calls = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for a in node.names:
                imported_symbols.add(a.name.lower())
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imported_symbols.add(node.module.lower())
            for a in node.names:
                imported_symbols.add(a.name.lower())
        elif isinstance(node, ast.Attribute):
            function_calls.add(node.attr.lower())
        elif isinstance(node, ast.Name):
            function_calls.add(node.id.lower())

    r1_failed = any(p in imported_symbols or p in function_calls for p in ["x25519", "ed25519", "rsa", "dsa"])
    if not log_result("1. No X25519/Ed25519 emulation used in crypto_engine.py", not r1_failed,
                      "Forbidden classical primitives found in AST!" if r1_failed else "Zero classical KEM/DSA imports or calls detected."):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 2: No SHAKE padding used to fake PQC key/signature lengths
    # --------------------------------------------------------------------------
    r2_failed = any("shake" in s for s in (imported_symbols | function_calls))
    if not log_result("2. No SHAKE padding to fake PQC key or signature lengths", not r2_failed,
                      "SHAKE length-extension padding found in AST!" if r2_failed else "True NIST key sizes generated by mathematical primitive."):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 3: Database User model does NOT define plaintext private key columns
    # --------------------------------------------------------------------------
    models_path = os.path.join(BACKEND_DIR, "app", "models", "database.py")
    with open(models_path, "r", encoding="utf-8") as f:
        models_code = f.read()

    r3_failed = ("kem_private_key" in models_code) or ("dsa_private_key" in models_code)
    if not log_result("3. Database models define NO plaintext private key columns", not r3_failed,
                      "Plaintext private key columns defined in database models!" if r3_failed else "Database models store only public keys, key IDs, and keystore paths."):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 4: SQLite Database schema has NO plaintext private key columns
    # --------------------------------------------------------------------------
    db_path = os.path.join(BACKEND_DIR, "ciphertrace_v2.db")
    r4_passed = True
    if os.path.exists(db_path):
        con = sqlite3.connect(db_path)
        cur = con.cursor()
        cur.execute("PRAGMA table_info(users)")
        cols = [c[1].lower() for c in cur.fetchall()]
        con.close()
        if "kem_private_key" in cols or "dsa_private_key" in cols:
            r4_passed = False

    if not log_result("4. SQLite users table contains NO plaintext private key columns", r4_passed,
                      "Database schema violation: private key columns exist on disk!" if not r4_passed else "All private keys absent from database tables."):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 5: Reed-Solomon implements genuine RS(255, 127) and not RSCodec(16)
    # --------------------------------------------------------------------------
    watermark_engine_path = os.path.join(BACKEND_DIR, "app", "services", "watermark_engine.py")
    with open(watermark_engine_path, "r", encoding="utf-8") as f:
        wm_code = f.read()

    r5_failed = ("RSCodec(16)" in wm_code) or ("RSCodec(self.PARITY_LEN)" not in wm_code and "RSCodec(128)" not in wm_code)
    if not log_result("5. Watermark engine implements genuine RS(255, 127) with 128 parity symbols", not r5_failed,
                      "Fake RSCodec(16) found in watermark engine!" if r5_failed else "RS(255, 127) with 128 parity bytes and 127-byte structured frame implemented."):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 6: Private keys are NEVER serialized into API schemas or Evidence Bundles
    # --------------------------------------------------------------------------
    schemas_path = os.path.join(BACKEND_DIR, "app", "schemas.py")
    with open(schemas_path, "r", encoding="utf-8") as f:
        schemas_code = f.read()

    r6_failed = ("kem_private_key" in schemas_code) or ("dsa_private_key" in schemas_code)
    if not log_result("6. API and Evidence schemas contain NO private key fields", not r6_failed,
                      "Private key fields exposed in API schemas!" if r6_failed else "API schemas expose only public metadata, key IDs, and verifiable evidence."):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 7: Encrypted Keystore Manager exists with Argon2id + AES-256-GCM
    # --------------------------------------------------------------------------
    keystore_path = os.path.join(BACKEND_DIR, "app", "services", "keystore.py")
    r7_passed = os.path.exists(keystore_path)
    if r7_passed:
        with open(keystore_path, "r", encoding="utf-8") as f:
            ks_code = f.read()
        r7_passed = ("argon2" in ks_code.lower()) and ("aesgcm" in ks_code.lower())

    if not log_result("7. Recipient Encrypted Keystore implemented with Argon2id KDF & AES-256-GCM", r7_passed,
                      "Keystore missing or lacks Argon2id/AES-GCM!" if not r7_passed else "Recipient-controlled encrypted keystores protect private keys."):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 8: Fail-Closed Blockchain Policy in SECURE_MODE
    # --------------------------------------------------------------------------
    ledger_client_path = os.path.join(BACKEND_DIR, "app", "services", "ledger_client.py")
    with open(ledger_client_path, "r", encoding="utf-8") as f:
        ledger_code = f.read()

    r8_passed = "LedgerOfflineError" in ledger_code and "SECURE_MODE" in ledger_code
    if not log_result("8. Fail-closed blockchain policy enforced when Fabric is offline in SECURE_MODE", r8_passed,
                      "Ledger client fails to enforce fail-closed security!" if not r8_passed else "SECURE_MODE refuses commit if consortium blockchain is unreachable."):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 9: Runtime PQC Cryptographic Self-Test
    # --------------------------------------------------------------------------
    from app.services.crypto_engine import CryptoEngine
    try:
        backend_info = CryptoEngine.get_backend_info()
        pqc_valid = CryptoEngine.verify_pqc_availability()
        r9_passed = (pqc_valid is True) and (backend_info["kem_algorithm"] == "ML-KEM-768") and (backend_info["signature_algorithm"] == "ML-DSA-65")
        detail = f"Active Backend: {backend_info['backend']} | FIPS 203 & 204 operational."
    except Exception as e:
        r9_passed = False
        detail = f"Self-test failed: {e}"

    if not log_result("9. Runtime PQC self-test verifies genuine ML-KEM-768 & ML-DSA-65 operations", r9_passed, detail):
        failures += 1

    # --------------------------------------------------------------------------
    # Rule 10: Docker & Offline Hyperledger Fabric network configuration exists
    # --------------------------------------------------------------------------
    compose_fabric = os.path.join(ROOT_DIR, "docker-compose.fabric.yml")
    chaincode_lib = os.path.join(ROOT_DIR, "blockchain", "chaincode", "forensic-audit", "lib", "forensicAudit.js")
    r10_passed = os.path.exists(compose_fabric) and os.path.exists(chaincode_lib)

    if not log_result("10. 3-Organization Hyperledger Fabric network & chaincode contract deployed", r10_passed,
                      "Fabric compose or chaincode missing!" if not r10_passed else "Multi-Org Consortium contract and 3-peer compose topology present."):
        failures += 1

    # --------------------------------------------------------------------------
    # Final Verdict
    # --------------------------------------------------------------------------
    print("=" * 80)
    if failures == 0:
        print("[SUCCESS] ALL 10 SECURITY REGRESSION AUDIT RULES PASSED.")
        print("          The repository satisfies all architectural defense constraints.")
        print("=" * 80)
        sys.exit(0)
    else:
        print(f"[FAILED] {failures} SECURITY REGRESSION AUDIT RULES FAILED.")
        print("         Remediate the reported violations before deploying.")
        print("=" * 80)
        sys.exit(1)


if __name__ == "__main__":
    main()
