#!/usr/bin/env python3
"""
CIPHERTRACE Automated Security Regression Audit Suite
===================================================
Enforces strict anti-regression rules to prevent security vulnerabilities
and false cryptographic claims from re-entering the repository.

Run from the repository root with the backend's Python environment:

    backend/.venv/bin/python scripts/security_audit.py

Exits with code 0 if all rules pass, or non-zero exit code if any rule fails.
"""

import ast
import os
import sqlite3
import sys

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BACKEND_DIR = os.path.join(ROOT_DIR, "backend")
APP_DIR = os.path.join(BACKEND_DIR, "app")
CHAINCODE_DIR = os.path.join(ROOT_DIR, "blockchain", "chaincode")
sys.path.insert(0, BACKEND_DIR)

PASS = "[PASS]"
FAIL = "[FAIL]"


def log_result(rule_name: str, passed: bool, detail: str = ""):
    status = PASS if passed else FAIL
    print(f"{status} Rule: {rule_name}")
    if detail:
        print(f"       -> {detail}")
    return passed


def read(*parts: str) -> str:
    path = os.path.join(*parts)
    if not os.path.exists(path):
        return ""
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def backend_sources():
    """(path, source) for every Python file under backend/app."""
    for root, _, files in os.walk(APP_DIR):
        for name in files:
            if name.endswith(".py"):
                path = os.path.join(root, name)
                yield path, read(path)


def main():
    print("=" * 80)
    print("      CIPHERTRACE AUTOMATED SECURITY REGRESSION AUDIT (SIH 2026)      ")
    print("=" * 80)

    results = []

    def rule(name: str, passed: bool, ok_detail: str, fail_detail: str):
        results.append(log_result(name, passed, ok_detail if passed else fail_detail))

    # --------------------------------------------------------------------------
    # Rule 1: No classical asymmetric algorithms imported or used as PQC
    # --------------------------------------------------------------------------
    crypto_code = read(APP_DIR, "services", "crypto_engine.py")
    tree = ast.parse(crypto_code)
    symbols = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            symbols.update(a.name.lower() for a in node.names)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                symbols.add(node.module.lower())
            symbols.update(a.name.lower() for a in node.names)
        elif isinstance(node, ast.Attribute):
            symbols.add(node.attr.lower())
        elif isinstance(node, ast.Name):
            symbols.add(node.id.lower())

    rule("1. No X25519/Ed25519/RSA emulation in crypto_engine.py",
         not any(p in symbols for p in ["x25519", "ed25519", "rsa", "dsa"]),
         "Zero classical KEM/DSA imports or calls detected.",
         "Forbidden classical primitives found in AST!")

    # --------------------------------------------------------------------------
    # Rule 2: No SHAKE padding used to fake PQC key/signature lengths
    # --------------------------------------------------------------------------
    rule("2. No SHAKE padding to fake PQC key or signature lengths",
         not any("shake" in s for s in symbols),
         "True NIST key sizes generated by mathematical primitive.",
         "SHAKE length-extension padding found in AST!")

    # --------------------------------------------------------------------------
    # Rule 3: Database models define no private key or passphrase columns
    # --------------------------------------------------------------------------
    models_code = read(APP_DIR, "models", "database.py")
    forbidden_columns = ["kem_private_key", "dsa_private_key", "keystore_password", "passphrase"]
    found = [c for c in forbidden_columns if c in models_code]
    rule("3. Database models define NO private key or passphrase columns",
         not found,
         "Models store only public keys, key IDs and keystore paths.",
         f"Forbidden columns in database models: {found}")

    # --------------------------------------------------------------------------
    # Rule 4: The configured database holds no private keys or stored passphrases
    # --------------------------------------------------------------------------
    from app.config import settings
    db_path = settings.DB_PATH
    r4_passed, detail = True, f"No database at {db_path} yet."
    if os.path.exists(db_path):
        try:
            con = sqlite3.connect(db_path)
            cur = con.cursor()
            cols = [c[1].lower() for c in cur.execute("PRAGMA table_info(users)").fetchall()]
            stored = 0
            if "keystore_password" in cols:
                # Legacy column from before passphrases; it must stay empty.
                stored = cur.execute("SELECT COUNT(*) FROM users WHERE keystore_password IS NOT NULL AND keystore_password != ''").fetchone()[0]
            con.close()
            if "kem_private_key" in cols or "dsa_private_key" in cols:
                r4_passed, detail = False, "Private key columns exist on disk!"
            elif stored:
                r4_passed, detail = False, f"{stored} user row(s) store a keystore passcode in plaintext!"
            else:
                detail = f"{db_path}: no private keys or stored passphrases."
        except sqlite3.DatabaseError as e:
            detail = f"Skipped: could not read {db_path} ({e})."
    rule("4. Configured database contains NO private keys or stored passphrases", r4_passed, detail, detail)

    # --------------------------------------------------------------------------
    # Rule 5: Watermark frame is authenticated, carries the ledger ID, and is redundant
    # --------------------------------------------------------------------------
    wm_code = read(APP_DIR, "services", "watermark_engine.py")
    authenticated = "hmac.new(" in wm_code and "sha3_256" in wm_code
    carries_ledger_id = "bytes.fromhex(watermark_id)[:10]" in wm_code
    redundant = "hadamard" in wm_code.lower() or ("RSCodec(" in wm_code and "RSCodec(0" not in wm_code)
    rule("5. Watermark frame carries the ledger watermark ID with an HMAC-SHA3-256 tag and redundant coding",
         authenticated and carries_ledger_id and redundant,
         "10-byte watermark ID + HMAC-SHA3-256 tag, spread with Hadamard/Reed-Solomon redundancy.",
         f"Watermark frame check failed (HMAC tag: {authenticated}, ledger ID: {carries_ledger_id}, redundancy: {redundant})")

    # --------------------------------------------------------------------------
    # Rule 6: Private keys and passphrases never appear in API schemas
    # --------------------------------------------------------------------------
    schemas_code = read(APP_DIR, "schemas.py")
    found = [f for f in ["kem_private_key", "dsa_private_key", "keystore_password", "passphrase"] if f in schemas_code]
    rule("6. API and evidence schemas contain NO private key or passphrase fields",
         not found,
         "API schemas expose only public metadata, key IDs and verifiable evidence.",
         f"Secret fields exposed in API schemas: {found}")

    # --------------------------------------------------------------------------
    # Rule 7: Encrypted keystore uses Argon2id + AES-256-GCM
    # --------------------------------------------------------------------------
    ks_code = read(APP_DIR, "services", "keystore.py").lower()
    rule("7. Keystore encrypted with Argon2id KDF & AES-256-GCM",
         "argon2" in ks_code and "aesgcm" in ks_code,
         "Private keys are protected by a passphrase-derived key.",
         "Keystore missing or lacks Argon2id/AES-GCM!")

    # --------------------------------------------------------------------------
    # Rule 8: The keystore passphrase lives only in memory
    # --------------------------------------------------------------------------
    session_code = read(APP_DIR, "services", "session_store.py")
    persists = any(p in session_code for p in ["open(", "sqlite", "write(", "json.dump"])
    rule("8. Keystore passphrase is kept in memory only, never persisted",
         bool(session_code) and not persists,
         "session_store.py holds passphrases in process memory with no file or database access.",
         "session_store.py is missing or writes passphrases somewhere!")

    # --------------------------------------------------------------------------
    # Rule 9: No decrypted copy is released without a ledger record
    # --------------------------------------------------------------------------
    ledger_engine_code = read(APP_DIR, "services", "ledger_engine.py")
    decryption_code = read(APP_DIR, "routers", "decryption.py")
    rule("9. Decrypted copies are withheld unless the ledger commit succeeds",
         "_withhold_copy" in ledger_engine_code and "LedgerCommitError" in ledger_engine_code
         and decryption_code.count("except LedgerCommitError") >= 2,
         "Failed ledger commits delete the watermarked copy and return 503.",
         "Fail-closed ledger commit is missing from ledger_engine.py or decryption.py!")

    # --------------------------------------------------------------------------
    # Rule 10: Runtime PQC cryptographic self-test
    # --------------------------------------------------------------------------
    from app.services.crypto_engine import CryptoEngine
    try:
        info = CryptoEngine.get_backend_info()
        r10_passed = (CryptoEngine.verify_pqc_availability() is True
                      and info["kem_algorithm"] == "ML-KEM-768"
                      and info["signature_algorithm"] == "ML-DSA-65")
        detail = f"Active backend: {info['backend']} | FIPS 203 & 204 operational."
    except Exception as e:
        r10_passed, detail = False, f"Self-test failed: {e}"
    rule("10. Runtime PQC self-test verifies genuine ML-KEM-768 & ML-DSA-65", r10_passed, detail, detail)

    # --------------------------------------------------------------------------
    # Rule 11: Both chaincodes bind every write to the submitting identity
    # --------------------------------------------------------------------------
    forensic_cc = read(CHAINCODE_DIR, "forensic-audit", "lib", "forensicAudit.js")
    keys_cc = read(CHAINCODE_DIR, "key-registry", "lib", "keyRegistry.js")
    setup_sh = read(ROOT_DIR, "blockchain", "scripts", "setup.sh")
    rule("11. Fabric chaincodes only accept records written by the user they name",
         "_assertSubmitterIsRecipient" in forensic_cc and "ALLOW_ADMIN_SUBMIT = false" in forensic_cc
         and "_assertSubmitterIs(" in keys_cc
         and '-ccn "$CC_NAME"' in setup_sh and '-ccn "$KEYS_CC_NAME"' in setup_sh,
         "forensic and keyregistry chaincodes enforce the certificate-name check and are both deployed.",
         "A chaincode is missing, its identity check is gone, or setup.sh does not deploy it!")

    # --------------------------------------------------------------------------
    # Rule 12: No unsafe archive extraction or key-leaking endpoints
    # --------------------------------------------------------------------------
    offenders = []
    for path, code in backend_sources():
        rel = os.path.relpath(path, ROOT_DIR)
        if "extractall(" in code:
            offenders.append(f"{rel}: zipfile.extractall")
        if '"key_hex"' in code or "/secure-upload" in code:
            offenders.append(f"{rel}: returns key material")
    rule("12. No unsafe zip extraction or key-leaking endpoints in the backend",
         not offenders,
         "Bundle uploads are unpacked with path checks; no endpoint returns key material.",
         "; ".join(offenders))

    # --------------------------------------------------------------------------
    # Final Verdict
    # --------------------------------------------------------------------------
    failures = results.count(False)
    print("=" * 80)
    if failures == 0:
        print(f"[SUCCESS] ALL {len(results)} SECURITY REGRESSION AUDIT RULES PASSED.")
        print("=" * 80)
        sys.exit(0)
    print(f"[FAILED] {failures} OF {len(results)} SECURITY REGRESSION AUDIT RULES FAILED.")
    print("         Remediate the reported violations before deploying.")
    print("=" * 80)
    sys.exit(1)


if __name__ == "__main__":
    main()
